# Generated by Django 4.1.7 on 2023-02-17 11:00

from django.db import migrations, models
import django.db.models.deletion
import first_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beeLine_Request_Number', models.CharField(max_length=30)),
                ('job_description', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=100)),
                ('no_of_positions', models.IntegerField()),
                ('priority', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('cv_DeadLine', models.DateField()),
                ('billing_Rate', models.CharField(max_length=100)),
                ('hours_per_week', models.IntegerField()),
                ('contact_person', models.CharField(max_length=30)),
                ('date_request', models.DateField()),
                ('file', models.FileField(blank=True, default='settings.MEDIA_ROOT/anonymous.jpg', null=True, upload_to=first_app.models.upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_Status', models.CharField(max_length=100)),
                ('name_of_candidate', models.CharField(max_length=100)),
                ('prodapt_practice', models.CharField(max_length=30)),
                ('prodapt_POC', models.CharField(max_length=50)),
                ('next_step', models.CharField(max_length=200)),
                ('dutch_Language', models.CharField(max_length=5)),
                ('location_relocation', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('client_Interview', models.CharField(max_length=5)),
                ('cv_Attachment', models.FileField(blank=True, null=True, upload_to=first_app.models.upload_path)),
                ('comments', models.CharField(default=False, max_length=1000)),
                ('beeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beeline', to='first_app.beeline')),
            ],
        ),
    ]
