# Generated by Django 4.1.7 on 2023-03-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dutch_Language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prodapt_POC',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prodapt_practice',
        ),
        migrations.AddField(
            model_name='beeline',
            name='dutch_Language',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='beeline',
            name='key_skills',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='beeline',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='beeline',
            name='prodapt_POC',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beeline',
            name='prodapt_practice',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
